# NLP - Bennett University Lab - 2
``Harsh Dubey - E20bca021``

* Create co-occurrence matrix
* SVD
* PCA and word2vec

In [38]:
import pandas as pd
import numpy as np

In [28]:
data = pd.read_csv("PoetryFoundationData.csv")
data.head()

,Unnamed: 0,Title,Poem,Poet,Tags
0,0,\r\r\n Objects Used to Prop...,"\r\r\nDog bone, stapler,\r\r\ncribbage board, ...",Michelle Menting,NaN
1,1,\r\r\n The New Church\r\r\n...,"\r\r\nThe old cupola glinted above the clouds,...",Lucia Cherciu,NaN
2,2,\r\r\n Look for Me\r\r\n ...,\r\r\nLook for me under the hood\r\r\nof that ...,Ted Kooser,NaN
3,3,\r\r\n Wild Life\r\r\n ...,"\r\r\nBehind the silo, the Mother Rabbit\r\r\n...",Grace Cavalieri,NaN
4,4,\r\r\n Umbrella\r\r\n ...,\r\r\nWhen I push your button\r\r\nyou fly off...,Connie Wanek,NaN

In [29]:
data.drop(["Unnamed: 0", "Tags", "Poet"], axis=1, inplace=True)
data.head()

,Title,Poem
0,\r\r\n Objects Used to Prop...,"\r\r\nDog bone, stapler,\r\r\ncribbage board, ..."
1,\r\r\n The New Church\r\r\n...,"\r\r\nThe old cupola glinted above the clouds,..."
2,\r\r\n Look for Me\r\r\n ...,\r\r\nLook for me under the hood\r\r\nof that ...
3,\r\r\n Wild Life\r\r\n ...,"\r\r\nBehind the silo, the Mother Rabbit\r\r\n..."
4,\r\r\n Umbrella\r\r\n ...,\r\r\nWhen I push your button\r\r\nyou fly off...

In [30]:
data.shape
tokens = {} # format words: [index_no, counts]

(13854, 2)

### Processing Text

In [34]:
index = 0

for i in data:
    for j in range(len(data[i])):
        words = data[i][j].split()
        for w in words:
            if w not in tokens:
                tokens[w] = [index, 1]
                index += 1
            else: tokens[w][1] += 1
        data[i][j] = " ".join(words).lstrip()
data.head()

,Title,Poem
0,Objects Used to Prop Open a Window,"Dog bone, stapler, cribbage board, garlic pres..."
1,The New Church,"The old cupola glinted above the clouds, shone..."
2,Look for Me,Look for me under the hood of that old Chevrol...
3,Wild Life,"Behind the silo, the Mother Rabbit hunches lik..."
4,Umbrella,When I push your button you fly off the handle...

In [37]:
print(len(tokens))

280450

In [ ]:
def co_occurrence_matrix(window_size=1):
    matrix = np.zeros((len(tokens), len(tokens)), np.float64)

In [40]:
print(data["Poem"][0])

Dog bone, stapler, cribbage board, garlic press because this window is loose—lacks suction, lacks grip. Bungee cord, bootstrap, dog leash, leather belt because this window had sash cords. They frayed. They broke. Feather duster, thatch of straw, empty bottle of Elmer's glue because this window is loud—its hinges clack open, clack shut. Stuffed bear, baby blanket, single crib newel because this window is split. It's dividing in two. Velvet moss, sagebrush, willow branch, robin's wing because this window, it's pane-less. It's only a frame of air.